---
title: "Sampling sites map"
output: html_notebook
---

Creating a map of the Rocky River, NL, including study sites for the 2024 field season. Code taken from Milos Makes Maps( https://www.youtube.com/watch?v=tlVNJTZO2js).

Load packages
```{r}
library(tidyverse)
library(httr)
library(sf)
```


Load data. Data is obtained from HydroSHEDS (https://www.hydrosheds.org/).
```{r}
get_data <- function(){
  url <- "https://data.hydrosheds.org/file/HydroRIVERS/HydroRIVERS_v10_na_shp.zip"
  res <- httr::GET(
    url,
    write_disk("na_river.zip"),
    progress()
  )
  unzip("na_river.zip")
  filenames <- list.files("HydroRIVERS_v10_na_shp",
                          pattern = "*.shp", full.names = TRUE
                          )
  
  return(filenames)
}

filenames <- get_data()
```

Create river width
```{r}
load_rivers <- function(){ #create object that we can manipulate to calculate width
  list_riv <- lapply(filenames, sf::st_read)
  na_riv <- list_riv[[1]] |> 
    sf::st_cast("MULTILINESTRING")
  
  return(na_riv)
}

na_riv <- load_rivers()
```
```{r}
set_river_width <- function() { #calculate width using new object
  na_riv_width <- na_riv |> 
    dplyr::mutate(
      width = as.numeric(ORD_FLOW),
      width = dplyr::case_when( #set width according to stream order
        width == 4 ~ 1,
        width == 3 ~ 0.8,
        width == 4 ~ 0.6,
        width == 5 ~ 0.4,
        width == 6 ~ 0.2,
        width == 7 ~ 0.2,
        width == 8 ~ 0.2,
        width == 9 ~ 0.1,
        width == 10 ~ 0.1,
        TRUE ~ 0
      )
    ) |> 
    sf::st_as_sf()
}

na_riv_width <- set_river_width()
```

Now we can set the boundaries of our map, which will focus on the southern Avalon Peninsula, NL.
```{r}
crsLONGLAT <- "+proj=longlat +datum=WGS84 +no_defs" #set coordinate system

get_bounding_box <- function() {
  bbox <- st_sfc(
    st_polygon(list(cbind(
      c(-53.637142, -53.387375, -53.387375, -53.637142, -53.637142),
      c(47.207581, 47.207581, 47.444320, 47.444320, 47.207581)
    ))),
    crs = crsLONGLAT
  )
  
  new_prj <- sf::st_transform(bbox, crs = 4087)
  bb <- sf::st_bbox(new_prj)
  
  return(bb)
}

bbox <- get_bounding_box()
```

Create the map now:
```{r}
get_river_map <- function() {
  p <- ggplot() +
    geom_sf(
      data = na_riv_width,
      aes(
        colour = factor(ORD_FLOW), size = width,
        alpha = factor(ORD_FLOW)
      )
    ) +
    coord_sf(
      crs = 4087,
      xlim = c(bbox["xmin"], bbox["xmax"]),
      ylim = c(bbox["ymin"], bbox["ymax"])
    ) +
    labs(
      y = "", subtitle = "",
      x = "",
      title = "",
      caption = ""
    ) +
    scale_colour_manual(
      name = "",
      values = c(
        "#08306b", "#08519c", "#2171b5",
                "#4292c6", "#6baed6", "#9ecae1",
                "#c6dbef", "#deebf7", "#c6d1ef"
      )
    ) +
    scale_size(range = c(0, 0.3)) +
    scale_alpha_manual(values = c(
      "3" = 1, "4" = 1, "5" = .7, "6" = .6,
            "7" = .4, "8" = .3, "9" = .2, "10" = .1
    )) +
    theme_minimal() +
    theme(
            panel.background = element_blank(),
            legend.background = element_blank(),
            legend.position = "none",
            panel.border = element_blank(),
            panel.grid.minor = element_blank(),
            panel.grid.major = element_blank(),
            plot.title = element_text(
                size = 40, color = "#2171b5", hjust = 0.5, vjust = 0
            ),
            plot.subtitle = element_text(
                size = 14, color = "#ac63a0", hjust = 0.5, vjust = 0
            ),
            plot.caption = element_text(
                size = 10, color = "grey60", hjust = 0.5, vjust = 10
            ),
            axis.title.x = element_text(
                size = 10, color = "grey20", hjust = 0.5, vjust = -6
            ),
            legend.text = element_text(
                size = 9, color = "grey20"
            ),
            legend.title = element_text(size = 10, color = "grey20"),
            strip.text = element_text(size = 12),
            plot.margin = unit(c(t = 1, r = -2, b = -1, l = -2), "lines"),
            axis.title.y = element_blank(),
            axis.ticks = element_blank(),
            axis.text.x = element_blank(),
            axis.text.y = element_blank()
        )
  
  return(p)
}

p1 <- get_river_map()

ggsave(
    filename = "avalon_rivers.png",
    width = 8.5, height = 7, dpi = 600,
    device = "png", bg = "white", p1
)
```

